name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: hasanalperen
  APP: githubaction

jobs:
  docker_build_and_push:
    name: docker
    runs-on: builder
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: app/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.APP }}:${{ github.run_id }}
  manifest_update:
    name: argocd
    runs-on: builder
    needs: ['docker_build_and_push']
    steps: 
      - name: check repository
        uses: actions/checkout@v4
        with: 
          repository: alperen-selcuk/githubaction-docker-argocd-kubernetes
          ref: main
          token: ${{ secrets.GIT_TOKEN }}
      - name: git_config
        run: |
          git config --global user.email "alperenhasanselcuk@gmail.com"
          git config --global user.name "alperen-selcuk"
          ls -la
          sed -i '' 's|hasanalperen/githubaction:.*|hasanalperen/githubaction:{{ github.run_id }}|' ./manifests/deployment.yaml
          cat manifests/deployment.yaml
          git add -A
          git commit -am "update manifest"
      - name: git_push
        run: |
          git push origin main
        
      
  
